### ISSUE TITLE
Failing to convert on Ubuntu 14.04

### ISSUE THREAD

**Issue by ryanswrt** [coolaj86/yaml2json#5]
Input

``` yaml
--- 
- 
  instrument: "Lasik 2000"
  pulseDuration: 12
  pulseEnergy: 5.4
  repetition: 1000
  spotSize: 1mm
- 
  instrument: "Lasik 2000"
  pulseDuration: 10
  pulseEnergy: 5.0
  repetition: 500
  spotSize: 2mm
```

Output:

```
/usr/local/lib/node_modules/yaml2json/node_modules/yaml/lib/yaml.js:179
  throw new Error(msg + ', ' + context(this.peek()[1].input))
        ^
Error: expected indent after document, near " \n- \n  instrument: \"Lasik"
    at Parser.expect (/usr/local/lib/node_modules/yaml2json/node_modules/yaml/lib/yaml.js:179:9)
    at Parser.parseDoc (/usr/local/lib/node_modules/yaml2json/node_modules/yaml/lib/yaml.js:264:8)
    at Parser.parse (/usr/local/lib/node_modules/yaml2json/node_modules/yaml/lib/yaml.js:232:19)
    at Object.exports.eval (/usr/local/lib/node_modules/yaml2json/node_modules/yaml/lib/yaml.js:384:46)
    at handleInput (/usr/local/lib/node_modules/yaml2json/index.js:31:17)
    at /usr/local/lib/node_modules/yaml2json/index.js:56:9
    at fs.js:268:14
    at Object.oncomplete (fs.js:107:15)
```

YAMLint.com says it's valid YAML, and conversion works on http://yamltojson.com/
