### ISSUE TITLE
Keep whitespaces and structure

### ISSUE THREAD

**Issue by zxqfox** [coolaj86/yaml2json#6]
Yaml:
```yaml
bla:
  yo: [1,2,3,4,5,6]
  foo: bar
  baz: {keep: me, one: lined}
```

Expected (roughly):
```json
{ "bla":
  { "yo": [1, 2, 3, 4, 5, 6],
    "foo": "bar",
    "baz": {"keep": "me", "one": "lined"}}}
```

But got:
```json
{
  "bla": {
    "yo": [
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "foo": "bar",
    "baz": {
      "keep": "me",
      "one": "lined"
    }
  }
}
```

Thoughs?
